apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: demo001coreshipping
  title: demo_001/core_shipping
  namespace: default
  description: Meta Collection for core_shipping
  annotations:
  labels:
    harness_org: demo_001
    harness_project: demo_001
  tags: []
  links: []
spec:
  type: app-system
  lifecycle: production
  owner: harness_account_all_users
  domain: demo001core