apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v26orchguestservice
  title: demo_001/v26-orch-guest-service
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v26orchguestservice?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v26orchguestservice
    application: guest
    domain: orch
    version: v26
  tags: 
    - v26-orch-guest-service
    - guest
    - orch
    - v26
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v26orchguestservice?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001orchguest