apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v8orchaccountprofile
  title: demo_001/v8-orch-account-profile
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v8orchaccountprofile?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v8orchaccountprofile
    application: account
    domain: orch
    version: v8
  tags: 
    - v8-orch-account-profile
    - account
    - orch
    - v8
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v8orchaccountprofile?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001orchaccount