apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v27infraalertsxcc
  title: demo_001/v27-infra-alerts-xcc
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v27infraalertsxcc?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v27infraalertsxcc
    application: alerts
    domain: infra
    version: v27
  tags: 
    - v27-infra-alerts-xcc
    - alerts
    - infra
    - v27
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v27infraalertsxcc?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001infraalerts