apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v3orchbuyorder
  title: demo_001/v3-orch-buy-order
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v3orchbuyorder?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v3orchbuyorder
    category: orch
    domain: buy
    version: v3
  tags: 
    - v3-orch-buy-order
    - orch
    - buy
    - v3
  links: 
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v3orchbuyorder?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  subcomponentOf: Component:default/demo001orchbuy