apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v19orchsubscriptionservice
  title: demo_001/v19-orch-subscription-service
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v19orchsubscriptionservice?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v19orchsubscriptionservice
    application: subscription
    domain: orch
    version: v19
  tags: 
    - v19-orch-subscription-service
    - subscription
    - orch
    - v19
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v19orchsubscriptionservice?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001orchsubscription