apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v26coresubscriptionservice
  title: demo_001/v26-core-subscription-service
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v26coresubscriptionservice?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v26coresubscriptionservice
    application: subscription
    domain: core
    version: v26
  tags: 
    - v26-core-subscription-service
    - subscription
    - core
    - v26
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v26coresubscriptionservice?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001coresubscription