apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v9coreaccountcustomerpublisher
  title: demo_001/v9-core-account-customerpublisher
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v9coreaccountcustomerpublisher?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v9coreaccountcustomerpublisher
    application: account
    domain: core
    version: v9
  tags: 
    - v9-core-account-customerpublisher
    - account
    - core
    - v9
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v9coreaccountcustomerpublisher?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001coreaccount