apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001v14corevliteservice
  title: demo_001/v14-core-vlite-service
  namespace: default
  description: Automatically registered Harness Service
  annotations:
    harness.io/services: |
      service: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v14corevliteservice?tab=summaryTab
  labels:
    harness_org: demo_001
    harness_project: demo_001
    harness_service: v14corevliteservice
    application: vlite
    domain: core
    version: v14
  tags: 
    - v14-core-vlite-service
    - vlite
    - core
    - v14
  links:
    - url: https://app.harness.io/ng/account/cNx_OWAtRhuiCWYmzqjqQQ/all/orgs/demo_001/projects/demo_001/settings/services/v14corevliteservice?tab=metrics
      title: Harness Service Metrics
      type: service-metric-dashboard
spec:
  type: service
  lifecycle: production
  owner: harness_account_all_users
  system: demo001corevlite