apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo001coreprice
  title: demo_001/core_price
  namespace: default
  description: Meta Collection for Core:Price
  labels:
    harness_org: demo_001
    harness_project: demo_001
  tags: []
  links: []
spec:
  type: app-domain
  lifecycle: production
  owner: harness_account_all_users
  subcomponentOf: Component:default/demo001core

